# Calls shared workflow to correct submodule URLs

# Github pushes are triggered by mirror operations from Gitlab.
# This workflow will only affect Github, not Gitlab.

name: Main Actions workflow

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  call-submodule-corrector:
    uses: tropicsquare/workflow-templates/.github/workflows/shared-correct-submodule-urls.yml@master
